services:
  jupyterlab:
    image: ean8fr/neurodash
    env_file:
      - .env
    ports:
      - "8890:8888"
    volumes:
      - ./:/neurodash
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - neuronetwork
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - neuronetwork
volumes:
  postgresdata:
networks:
  neuronetwork: